title: "Surya Pradipa Warren"
logo: /assets/img/foto.jpg  # Pastikan file ini ada dan sesuai path-nya
description: "Portfolio of an Informatics Engineering Graduate | Software Developer & Machine Learning Enthusiast"
show_downloads: false  # Set ke true jika kamu ingin munculkan tombol download ZIP
theme: jekyll-theme-minimal

# Optional enhancements (diaktifkan jika kamu menggunakan plugin Jekyll tambahan):
# google_analytics: UA-XXXXXXXXX-X  # Ganti dengan ID Google Analytics jika ada
social_links:
   github: suryaPradipaWarren
   linkedin: Surya Pradipa Warren
   email: suryapradipawarren@gmail.com

